name: 'Verify WASI ABI files are up-to-date'
description: 'Verify WASI ABI files are up-to-date'

inputs:
  wit-bindgen:
    description: 'version of the `wit-bindgen` tool to use'
    required: false
    default: '0.11.0'

runs:
  using: composite
  steps:
    - name: Install wit-bindgen
      shell: bash
      run: cargo install wit-bindgen@${{ inputs.wit-bindgen }}
